# Generated by Django 6.0.2 on 2026-02-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('assign', 'Assign'), ('status_change', 'Status Change'), ('upload', 'File Upload')], max_length=20)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/%Y/%m/%d/')),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evidence',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('incident_type', models.CharField(choices=[('theft', 'Theft/Burglary'), ('suspicious', 'Suspicious Activity'), ('vandalism', 'Vandalism'), ('lost_found', 'Lost and Found'), ('noise', 'Noise Complaint'), ('facility', 'Facility Issue'), ('traffic', 'Traffic Incident'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location_building', models.CharField(max_length=100)),
                ('location_floor', models.CharField(blank=True, max_length=50)),
                ('location_details', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('is_public_report', models.BooleanField(default=False)),
                ('reporter_name', models.CharField(blank=True, max_length=100)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'incident_notes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('incident_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('location_building', models.CharField(max_length=100)),
                ('location_floor', models.CharField(blank=True, max_length=50)),
                ('reporter_name', models.CharField(blank=True, max_length=100)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(default='received', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'public_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
